"use client"
import './globals.css'
import { Raleway } from 'next/font/google'
import { SessionProvider } from 'next-auth/react'
import Navbar from 'components/Navbar'
import { useEffect , useState } from 'react'
import { UserLocationContext } from '@/context/UserLocationContext'
import { SelectedBusinessContext } from '@/context/SelectedBusinessContext'

const raleway = Raleway({ subsets: ['latin'] })

const metadata = {
  title: 'Tubeguruji',
  description: 'Generated by Tubeguruji',
}

export default function RootLayout({ children }) {


  const [userLocation, setUserLocation] = useState({})
  const [selectedBusiness, setSelectedBusiness] = useState([])

  useEffect(()=>{
    getUserLocation();
  },[])

  const getUserLocation=()=>{
    navigator.geolocation.getCurrentPosition(function(pos){
      console.log(pos)
      setUserLocation({
        lat:pos.coords.latitude,
        lng:pos.coords.longitude
      })
    })
  }
  
  console.log(2,"layout.js","state userLocation :",userLocation);

  return (
    <html lang="en">
      <body className={raleway.className}>
        <SessionProvider>
          <SelectedBusinessContext.Provider value={{selectedBusiness,setSelectedBusiness}}>
          <UserLocationContext.Provider value={{userLocation,setUserLocation}}>
            <Navbar/>
            {children}
          </UserLocationContext.Provider>
          </SelectedBusinessContext.Provider>
        </SessionProvider>
      </body>
    </html>
  )
}
